# Generated by Django 4.0.4 on 2022-05-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civ', models.CharField(max_length=80)),
                ('civ_id', models.IntegerField()),
            ],
        ),
    ]
