# Generated by Django 4.0.4 on 2022-06-05 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoe2net_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('lobby_id', models.IntegerField(null=True)),
                ('match_uuid', models.CharField(max_length=80)),
                ('version', models.CharField(max_length=80, null=True)),
                ('name', models.CharField(max_length=80, null=True)),
                ('num_players', models.IntegerField()),
                ('num_slots', models.IntegerField()),
                ('average_rating', models.IntegerField(null=True)),
                ('cheats', models.BooleanField(default=False)),
                ('full_tech_tree', models.BooleanField(default=False)),
                ('ending_age', models.IntegerField(null=True)),
                ('expansion', models.CharField(max_length=80, null=True)),
                ('game_type', models.IntegerField()),
                ('has_custom_content', models.BooleanField(null=True)),
                ('has_password', models.BooleanField(null=True)),
                ('lock_speed', models.BooleanField(default=True)),
                ('lock_teams', models.BooleanField(default=True)),
                ('map_size', models.IntegerField()),
                ('population', models.IntegerField()),
                ('ranked', models.BooleanField(null=True)),
                ('leaderboard_id', models.IntegerField()),
                ('rating_type', models.IntegerField()),
                ('resources', models.IntegerField()),
                ('rms', models.CharField(max_length=80, null=True)),
                ('scenario', models.CharField(max_length=80, null=True)),
                ('server', models.CharField(max_length=80, null=True)),
                ('shared_exploration', models.BooleanField(default=False)),
                ('speed', models.IntegerField()),
                ('starting_age', models.IntegerField()),
                ('team_together', models.BooleanField(default=True)),
                ('team_positions', models.BooleanField(default=True)),
                ('treaty_length', models.IntegerField()),
                ('turbo', models.BooleanField(default=False)),
                ('victory', models.IntegerField()),
                ('victory_time', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('opened', models.IntegerField()),
                ('started', models.IntegerField()),
                ('finished', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='civ_alpha_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='clan',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='color',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='country',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='drops',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='games',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='profile_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='rating_change',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='slot',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='slot_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='steam_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='streak',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='team',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='wins',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='won',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='aoe2net_database.match'),
            preserve_default=False,
        ),
    ]
