# Generated by Django 4.0.4 on 2022-06-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoe2net_database', '0002_match_playermatchstat_civ_alpha_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='map',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='map_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
