# Generated by Django 4.0.4 on 2022-06-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoe2net_database', '0003_match_map_match_map_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='aoe2net_database.player'),
            preserve_default=False,
        ),
    ]
