# Generated by Django 4.0.4 on 2022-06-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoe2net_database', '0004_player_playermatchstat_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='expansion',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='map',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_uuid',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='match',
            name='name',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='rms',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='scenario',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='server',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='version',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstat',
            name='civ',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='playermatchstat',
            name='clan',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstat',
            name='country',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstat',
            name='name',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
