# Generated by Django 4.0.4 on 2022-06-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoe2net_database', '0005_alter_match_expansion_alter_match_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='resources',
            field=models.IntegerField(null=True),
        ),
    ]
