# Generated by Django 4.0.4 on 2022-08-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoe2net_database', '0008_alter_match_full_tech_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_type',
            field=models.IntegerField(null=True),
        ),
    ]
