# Generated by Django 4.0.4 on 2022-08-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoe2net_database', '0009_alter_match_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='lock_speed',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='lock_teams',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
