# Generated by Django 4.0.4 on 2022-08-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoe2net_database', '0012_alter_match_shared_exploration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='starting_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_positions',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_together',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='treaty_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='turbo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='victory',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='victory_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='visibility',
            field=models.IntegerField(null=True),
        ),
    ]
