# Generated by Django 4.0.4 on 2022-08-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoe2net_database', '0013_alter_match_speed_alter_match_starting_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='finished',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='lobby_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='opened',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='started',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='playermatchstat',
            name='profile_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstat',
            name='steam_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
